import {checkExploration} from './check-exploration.mjs';
import {checkShopVisits} from './check-shop-visits.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const dom=new Map(),listeners={};function element(){return {textContent:'',innerHTML:'',dataset:{},style:{},handlers:{},getBoundingClientRect(){return {left:24,top:500,width:112,height:112}},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},addEventListener(k,f){this.handlers[k]=f},setPointerCapture(){},click(){this.onclick?.()}}}
globalThis.document={addEventListener(k,f){listeners[k]=f},querySelector(s){if(!dom.has(s))dom.set(s,element());return dom.get(s)},querySelectorAll(){return []},body:{...element()},createElement(){return {...element(),getContext(){return {createLinearGradient(){return {addColorStop(){}}},fillRect(){}}}}}};globalThis.matchMedia=()=>({matches:false});globalThis.innerWidth=1280;globalThis.innerHeight=800;globalThis.devicePixelRatio=1;globalThis.window=globalThis;globalThis.addEventListener=(k,f)=>listeners[k]=f;
globalThis.__renderer={setPixelRatio(){},setSize(){},shadowMap:{},domElement:element(),render(scene,camera){scene.updateMatrixWorld(true);assert(camera.position.toArray().every(Number.isFinite))}};globalThis.__controls={target:new T.Vector3(),update(){}};
let next;globalThis.requestAnimationFrame=f=>next=f;GLTFLoader.prototype.loadAsync=async function(path){const b=fs.readFileSync(new URL('../../dist/'+path.replace('./',''),import.meta.url));return this.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')};globalThis.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL('../../dist/assets/sannenzaka/map.json',import.meta.url)))});
await import('../../dist/sannen-main.js');const d=globalThis.__sannenDebug,pointer=globalThis.__renderer.domElement.handlers;assert(d.ready);let now=0;
const initiallyOpen=d.town.homes.filter(h=>d.art.doorStates[h.id]>.99);
assert(initiallyOpen.length>=10&&initiallyOpen.length<=16,'About a third of the 39 accessible shops must start visibly open');
assert(d.town.buildings.filter(h=>!h.accessible).every(h=>d.art.doorStates[h.id]===0),'Inaccessible scenery doors must start closed');
assert.equal(d.people.filter(p=>p.visitsShops).length,10,'Only a third of pedestrians should visit shops');
// Interactions share production callbacks. Rendering itself is intentionally not mocked as a pass.
const closedDoor=d.art.doorStates.findIndex(s=>s===0);d.toggleDoor(closedDoor);for(let i=0;i<25;i++){now+=50;next(now)}assert(d.art.doorStates[closedDoor]>.9);dom.get('#pause').click();const frozen=d.state.simTime;next(now+10);assert.equal(d.state.simTime,frozen);dom.get('#pause').click();
for(let i=0;i<9000;i++){now+=50;next(now);if(i===20)d.setFollow(true);if(i===25)dom.get('#next-person').click();if(i===28)d.setFollow(false)}
assert(d.events.arrivals>0);assert(d.events.departures>0);for(const p of d.people){assert(p.g.position.toArray().every(Number.isFinite));assert(p.limbs.every(Boolean))}let meshes=0,instances=0;d.scene.traverse(o=>{if(o.isMesh){meshes++;if(o.isInstancedMesh){instances+=o.count;const mx=new T.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,mx);assert(mx.elements.every(Number.isFinite))}}}});
// Exercise the real pointer handler and raycast against the exported sliding door geometry.
d.art.doorTargets.fill(0);d.art.update(d.state.simTime,5);d.scene.updateMatrixWorld(true);
const h=d.town.homes[0];d.camera.position.copy(h.local(1.65,1.2,5));d.camera.lookAt(h.local(1.65,1.2,3.5));d.camera.updateMatrixWorld(true);
const clicks=d.events.doorClicks;pointer.pointerdown({clientX:640,clientY:400,pointerId:1});pointer.pointerup({clientX:640,clientY:400,pointerId:1});assert.equal(d.events.doorClicks,clicks+1,'Door pointer ray must hit its visible leaf');
pointer.pointerdown({clientX:640,clientY:400,pointerId:2});pointer.pointermove({clientX:670,clientY:400,pointerId:2});pointer.pointerup({clientX:640,clientY:400,pointerId:2});assert.equal(d.events.doorClicks,clicks+1,'Dragging must not click a door');
assert(d.events.doorWaitFrames>0);assert(d.events.stairFrames>0);assert.equal(d.art.stats.lightPools,4);assert(d.art.stats.bicycleParking>0);
// Pausing must freeze actual model matrices as well as simulation time.
next(now+=50);dom.get('#pause').click();const tracked=[];d.art.root.traverse(o=>{if(o.isInstancedMesh)tracked.push([o,o.instanceMatrix.version])});const before=d.people.map(p=>p.g.position.clone());next(now+=50);for(const [o,v]of tracked)assert.equal(o.instanceMatrix.version,v);d.people.forEach((p,i)=>assert(p.g.position.equals(before[i])));dom.get('#pause').click();
const shopVisits=checkShopVisits(d,()=>next(now+=50));console.log({shopVisits});
const exploration=checkExploration(d,dom,listeners,pointer,()=>next(now+=50));fs.writeFileSync(new URL('./exploration-check.json',import.meta.url),JSON.stringify(exploration,null,2));
const report={pass:true,shopVisits,exploration,virtualSeconds:d.state.simTime,events:d.events,people:d.people.length,meshes,instances,stats:d.art.stats,checks:['GLTFLoader reads native architecture and residents','All instances finite','Manual sliding door opens','Pause freezes simulation','Arrivals and departures','Follow camera and next visitor','Native limb pivots','Pointer raycast opens visible shop door','Dragging does not trigger door click','Pedestrians wait for open doors and slow on stairs','Pause freezes matrices and positions','Four lantern light pools and bicycle parking'],limitation:'Node DOM/renderer stubs; not browser WebGL rendering or mobile performance.'};fs.writeFileSync(new URL('./runtime-check.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
// Preserve the actual assembled geometry and transforms for an offline Blender audit.
if(process.env.EXPORT_RENDER==='1'){
 const geometries={},materials={},objects=[];const views={};for(const name of ['overview','sannen','ninen','yasaka']){d.view(name);views[name]=[d.camera.position.toArray(),globalThis.__controls.target.toArray()]}fs.writeFileSync(new URL('./camera-views.json',import.meta.url),JSON.stringify(views));d.scene.updateMatrixWorld(true);
 d.scene.traverse(o=>{if(!o.isMesh||!o.visible)return;const g=o.geometry,m=o.material;if(!geometries[g.uuid])geometries[g.uuid]={positions:Array.from(g.attributes.position.array),colors:g.attributes.color?Array.from(g.attributes.color.array):null,indices:g.index?Array.from(g.index.array):null};if(!materials[m.uuid])materials[m.uuid]={name:m.name,color:m.color.toArray(),opacity:m.opacity,emissive:m.emissive?.toArray(),emissiveIntensity:m.emissiveIntensity};
  if(o.isInstancedMesh){const mx=new T.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,mx);objects.push({geometry:g.uuid,material:m.uuid,matrix:o.matrixWorld.clone().multiply(mx).toArray()})}}else objects.push({geometry:g.uuid,material:m.uuid,matrix:o.matrixWorld.toArray()});
 });fs.writeFileSync(new URL('./composition.json',import.meta.url),JSON.stringify({geometries,materials,objects}));console.log('Actual runtime geometry exported',objects.length)
}
